version: '3.8'
services:
  elasticsearch1:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.8.12
    container_name: elasticsearch1
    environment:
      - cluster.name=docker-cluster
      - node.name=elasticsearch1
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.zen.minimum_master_nodes=2
      - "discovery.zen.ping.unicast.hosts=elasticsearch1,elasticsearch2"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - esnet
  elasticsearch2:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.8.12
    container_name: elasticsearch2
    environment:
      - cluster.name=docker-cluster
      - node.name=elasticsearch2
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "discovery.zen.ping.unicast.hosts=elasticsearch1,elasticsearch2"
      - "discovery.zen.minimum_master_nodes=2"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata2:/usr/share/elasticsearch/data
    ports:
      - 9200
    # for internal services such as kibana
    expose: 
      - 9200
    networks:
      - esnet
    depends_on:
      - elasticsearch1
  elasticsearch3:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.8.12
    container_name: elasticsearch3
    environment:
      - cluster.name=docker-cluster
      - node.name=elasticsearch3
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "discovery.zen.ping.unicast.hosts=elasticsearch1,elasticsearch2"
      - "discovery.zen.minimum_master_nodes=2"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata3:/usr/share/elasticsearch/data
    ports:
      - 9200
    networks:
      - esnet
    depends_on:
      - elasticsearch1
      - elasticsearch2
  datanode1:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.8.12
    container_name: datanode1
    environment:
      - cluster.name=docker-cluster
      - node.name=datanode1
      - node.master=false
      - node.data=true
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "discovery.zen.ping.unicast.hosts=elasticsearch1,elasticsearch2"
      - "discovery.zen.minimum_master_nodes=2"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - datanode1:/usr/share/elasticsearch/data
    ports:
      - 9200
    networks:
      - esnet
    depends_on:
      - elasticsearch1
      - elasticsearch2
      - elasticsearch3
  clientnode1:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.8.12
    container_name: clientnode1
    environment:
      - cluster.name=docker-cluster
      - node.name=clientnode1
      - node.master=false
      - node.data=false
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "discovery.zen.ping.unicast.hosts=elasticsearch1,elasticsearch2"
      - "discovery.zen.minimum_master_nodes=2"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - clientnode1:/usr/share/elasticsearch/data
    ports:
      - 9200
    networks:
      - esnet
    depends_on:
      - elasticsearch1
      - elasticsearch2
      - elasticsearch3      
  kibana:
    image: 'docker.elastic.co/kibana/kibana:6.8.12'
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=["http://clientnode1:9200","http://elasticsearch1:9200","http://elasticsearch2:9200"]
      - xpack.monitoring.collection.enabled=true
    ports:
      - '5601:5601'
    networks:
      - esnet
    depends_on:
      - elasticsearch1
      - elasticsearch2
      - elasticsearch3
      - datanode1
volumes:
  esdata1:
    driver: local
  esdata2:
    driver: local
  esdata3:
    driver: local
  datanode1:
    driver: local
  clientnode1:
    driver: local


networks:
  esnet:
